export const studentsActivesTest = [
    {
        "id":1,
        "matricula":"163174",
        "nombre":"Jesús Alberto",
        "apellido":"Gonzalez",
        "status":"ordinario",
        "avatar":"https://image.flaticon.com/icons/svg/201/201565.svg"
    },
    {
        "id":2,
        "matricula":"171152",
        "nombre":"Adrian",
        "apellido":"Morales",
        "status":"ordinario",
        "avatar":"https://image.flaticon.com/icons/svg/201/201565.svg"
    },
    {
        "id":3,
        "matricula":"171122",
        "nombre":"Miltón",
        "apellido":"Hernandez",
        "status":"ordinario",
        "avatar":"https://image.flaticon.com/icons/svg/201/201565.svg"
    },
    {
        "id":4,
        "matricula":"171112",
        "nombre":"Alexis",
        "apellido":"Bartolón",
        "status":"ordinario",
        "avatar":"https://image.flaticon.com/icons/svg/201/201565.svg"
    },
    {
        "id":5,
        "matricula":"171235",
        "nombre":"Linderman",
        "apellido":"Ordoñez",
        "status":"ordinario",
        "avatar":"https://image.flaticon.com/icons/svg/201/201565.svg"
    },
    {
        "id":6,
        "matricula":"163173",
        "nombre":"Eliezer",
        "apellido":"Jerez",
        "status":"ordinario",
        "avatar":"https://image.flaticon.com/icons/svg/201/201565.svg"
    }
];